version: "{build}"

pull_requests:
  do_not_increment_build_number: true
  
branches:
  only:
  - main
  
skip_non_tags: true

image: Visual Studio 2019

build_script:
  - cmd: git submodule update --init --recursive
  - cmd: nuget restore
  - cmd: msbuild /p:Configuration=Release /p:Platform="Any CPU"

test: off

artifacts:
  - path: 'SkyblockClient\bin\Release\*.exe'
